# Generated by Django 5.2.1 on 2025-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(help_text='First name of the record holder', max_length=50)),
                ('last_name', models.CharField(help_text='Last name of the record holder', max_length=50)),
                ('email', models.EmailField(help_text='Email address of the record holder (must be unique)', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the record holder (e.g., +91-XXXXXXXXXX)', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Full address of the record holder', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City of the record holder', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province of the record holder', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='Pincode or Zip code of the record holder', max_length=10)),
            ],
        ),
    ]
